const TelegramBot           = require('node-telegram-bot-api')
const ProductsController    = require('./controllers/products.controller')
const AuthController        = require('./controllers/auth.controller')
require('dotenv').config()
const bot                   = new TelegramBot(process.env.TOKEN, {polling: true})
const productsController    = new ProductsController(bot)
const authController        = new AuthController(bot)

bot.onText(/\/start/,       productsController.getList)
bot.onText(/\/list/,        productsController.getList)
bot.on('callback_query',    productsController.handleCallback)
bot.onText(/\/signup +(.)/, authController.signup)
